package com.sofacity.laichushu.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CACHE__JSON".
 */
public class Cache_Json {

    private Long id;
    private String inter;
    private String json;

    public Cache_Json() {
    }

    public Cache_Json(Long id) {
        this.id = id;
    }

    public Cache_Json(Long id, String inter, String json) {
        this.id = id;
        this.inter = inter;
        this.json = json;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getInter() {
        return inter;
    }

    public void setInter(String inter) {
        this.inter = inter;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

}
