package com.sofacity.laichushu.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sofacity.laichushu.db.Search_History;

import com.sofacity.laichushu.db.Search_HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig search_HistoryDaoConfig;

    private final Search_HistoryDao search_HistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        search_HistoryDaoConfig = daoConfigMap.get(Search_HistoryDao.class).clone();
        search_HistoryDaoConfig.initIdentityScope(type);

        search_HistoryDao = new Search_HistoryDao(search_HistoryDaoConfig, this);

        registerDao(Search_History.class, search_HistoryDao);
    }
    
    public void clear() {
        search_HistoryDaoConfig.getIdentityScope().clear();
    }

    public Search_HistoryDao getSearch_HistoryDao() {
        return search_HistoryDao;
    }

}
