package com.laichushu.book.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY__ID".
 */
public class City_Id {

    private Long id;
    private String province;
    private String city;
    private Integer proCode;
    private Integer cityCode;

    public City_Id() {
    }

    public City_Id(Long id) {
        this.id = id;
    }

    public City_Id(Long id, String province, String city, Integer proCode, Integer cityCode) {
        this.id = id;
        this.province = province;
        this.city = city;
        this.proCode = proCode;
        this.cityCode = cityCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getProCode() {
        return proCode;
    }

    public void setProCode(Integer proCode) {
        this.proCode = proCode;
    }

    public Integer getCityCode() {
        return cityCode;
    }

    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

}
