package com.laichushu.book.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.laichushu.book.db.Search_History;
import com.laichushu.book.db.Cache_Json;
import com.laichushu.book.db.City_Id;

import com.laichushu.book.db.Search_HistoryDao;
import com.laichushu.book.db.Cache_JsonDao;
import com.laichushu.book.db.City_IdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig search_HistoryDaoConfig;
    private final DaoConfig cache_JsonDaoConfig;
    private final DaoConfig city_IdDaoConfig;

    private final Search_HistoryDao search_HistoryDao;
    private final Cache_JsonDao cache_JsonDao;
    private final City_IdDao city_IdDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        search_HistoryDaoConfig = daoConfigMap.get(Search_HistoryDao.class).clone();
        search_HistoryDaoConfig.initIdentityScope(type);

        cache_JsonDaoConfig = daoConfigMap.get(Cache_JsonDao.class).clone();
        cache_JsonDaoConfig.initIdentityScope(type);

        city_IdDaoConfig = daoConfigMap.get(City_IdDao.class).clone();
        city_IdDaoConfig.initIdentityScope(type);

        search_HistoryDao = new Search_HistoryDao(search_HistoryDaoConfig, this);
        cache_JsonDao = new Cache_JsonDao(cache_JsonDaoConfig, this);
        city_IdDao = new City_IdDao(city_IdDaoConfig, this);

        registerDao(Search_History.class, search_HistoryDao);
        registerDao(Cache_Json.class, cache_JsonDao);
        registerDao(City_Id.class, city_IdDao);
    }
    
    public void clear() {
        search_HistoryDaoConfig.getIdentityScope().clear();
        cache_JsonDaoConfig.getIdentityScope().clear();
        city_IdDaoConfig.getIdentityScope().clear();
    }

    public Search_HistoryDao getSearch_HistoryDao() {
        return search_HistoryDao;
    }

    public Cache_JsonDao getCache_JsonDao() {
        return cache_JsonDao;
    }

    public City_IdDao getCity_IdDao() {
        return city_IdDao;
    }

}
