package com.laichushu.book.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH__HISTORY".
 */
public class Search_History {

    private Long id;
    private String type;
    private String history;

    public Search_History() {
    }

    public Search_History(Long id) {
        this.id = id;
    }

    public Search_History(Long id, String type, String history) {
        this.id = id;
        this.type = type;
        this.history = history;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getHistory() {
        return history;
    }

    public void setHistory(String history) {
        this.history = history;
    }

}
